name: platform
version: 1.0.0
config-version: 2

profile: platform

model-paths: [models]
target-path: target
clean-targets: [target, dbt_packages]

models:
  platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
      mart_portfolio_summary:
        +tags: [report]
      mart_policy_detail:
        +tags: [report]
      fact_policies:
        +tags: [report]
      dim_partner:
        +tags: [report]
      dim_product:
        +tags: [report]
      mart_management_kpi:
        +tags: [mgmt-report]
      mart_partner_growth:
        +tags: [mgmt-report]
      mart_product_performance:
        +tags: [mgmt-report]
      mart_policy_trend:
        +tags: [mgmt-report]
      mart_exposure_by_product:
        +tags: [mgmt-report]
