apiVersion: v1
kind: Secret
metadata:
  name: db-passwords
  namespace: datamesh
type: Opaque
stringData:
  partner-db-password: "1345234tqewg43!G34ffass"
  product-db-password: "agr32rfsad23_ar2A"
  policy-db-password: "lkajsdö32807sadcb3_asdvSAFWDGd"
  claims-db-password: "claims_dev_pw_42x!"
  billing-db-password: "billing_dev_pw_42x!"
  hr-db-password: "hr_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-config
  namespace: datamesh
type: Opaque
stringData:
  vault-token: "dev-root-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-config
  namespace: datamesh
type: Opaque
stringData:
  admin-password: "admin"
  oidc-client-secret: "secret"
