global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'partner-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['partner-service:9080']
  - job_name: 'product-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['product-service:9081']
  - job_name: 'policy-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['policy-service:9082']
  - job_name: 'claims-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['claims-service:9083']
  - job_name: 'billing-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['billing-service:9084']
  - job_name: 'hr-integration'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['hr-integration:9086']
